### ISSUE TITLE
Second Device in Scene Not Switching

### ISSUE THREAD

**Issue by andykartman** [n8henrie/homebridge-rcswitch-gpiomem#3]
Thanks for the great plugin. Seems to be running really well for me. One issue I have though, not sure it a plugin / homebridge or Apple Home issue.

I am using the new apple Home App on IOS 10, and I have 3 x watts clever power sockets running. All the on / off switching works flawlessly, except in the Scenes. If I have two of the sockets doing something in the Scene, only the first socket that was added to the scene will switch according to the scene requirements. 

I don't have that issue with other items such as my milights which also run on homebridge. I can have mulitple of those in the scene and they switch OK.

Maybe a timing thing? I have also noticed if I turn the switch on and off very quickly via the app it also misses the signal, which also does not happen with the milights.

Any clues on what I could do to resolve the issue? Can I add a slight delay somehow in between signals being sent?

Many thanks

**Comment by n8henrie** [comment]
Huh, I've never used Scenes. Did they exist before iOS10? I may have to check this out once I update to see if I can reproduce the issue.

Yes, I imagine it may have to do with trying to switch them all at once.

**Comment by andykartman** [comment]
Thanks for the reply.

Scenes are part of the new Apple Home App that has now been included with the IOS 10 (beta at the moment).

**Comment by n8henrie** [comment]
Well, I will definitely take a look at this once I upgrade to iOS 10, but that likely won't be before the official release. Sorry for the delay. If you find a workaround in the meantime please update here or send a PR.

**Comment by andykartman** [comment]
Ok, Thanks

**Comment by n8henrie** [comment]
iOS 10 installed -- I can confirm the issue.

**Comment by n8henrie** [comment]
Oddly, Homebridge's debug output thinks the switches are getting called, but I'm not seeing any output at all with [RFSniffer](https://github.com/n8henrie/rf_pi), as if they weren't doing anything at all... but occasionally one of the switches works, so I know it is. Odd.

**Comment by n8henrie** [comment]
Sorry for the extended delay. @andykartman -- any updates since September on your end?

Thinking through this, I really wonder if it may be an issue with Homebridge calling both switches in the scene simultaneously, making the transmitter (especially with its default number of repeats) try to call both switches at the same time and mucking up the signal.

Maybe -- at least for debugging -- I could add a small random delay between each transmission? Though I wonder -- if this is indeed the problem -- if a better solution might be upstream in Homebridge, having it call devices in a scene in serial instead of async / simultaneously (assuming it doesn't do this already).

**Comment by n8henrie** [comment]
I can no longer replicate with homebridge 0.4.16 and homebridge-rcswitch-gpiomem, a scene with 2 of my RCSwitch accessories is working reliably. @andykartman can you update and try again?

Given no updates since September and now working for me, I am going to go ahead and close -- will reopen if needed.

**Comment by andykartman** [comment]
Thanks for the update.  Traveling at the moment but will update and check next week.
